### PR TITLE
Issue/15 scheduling

### PR DESCRIPTION
**Pull request by weining-li**
starting time increases by increments of 15 minutes

no tests yet :<

#15

### CODE REVIEW

**Review by ToanQVu — CHANGES_REQUESTED** [review]
You need semicolon for all.

**Comment by ToanQVu** [comment]
Do `yarn install` to install dependencies and add Eslint to your editor to see the error code.

**Comment by ToanQVu** [comment]
Use Prettier to format your code for a better quality of life.

**Comment by weining-li** [comment]
i hope there's one called Manlier where semicolons are banned

**Review by ToanQVu — APPROVED** [review]

**Pull request merged**
